const data = {
  products: [
    {
      _id: '1',
      name: 'Hard Copy Bond Paper',
      slug: 'hardcopy-letter-bond-paper',
      category: 'Office Supplies',
      size: 'letter (8.5"x 11")',
      image: '/images/p1.jpg',
      price: 187.98,
      countInStock: 10,
      brand: 'Dong-A',
      rating: 4.2,
      numReviews: 10,
      description: 'subs-20/70gsm, high quality bond paper',
    },
    {
      _id: '2',
      name: 'Hard Copy Bond Paper',
      slug: 'hardcopy-legal-bond-paper',
      category: 'Office Supplies',
      size: 'legal (8.5"x 14")',
      image: '/images/p2.jpg',
      price: 217.99,
      countInStock: 20,
      brand: 'Dong-A',
      rating: 4.59,
      numReviews: 25,
      description: 'subs-20/70gsm, high quality bond paper',
    },
    {
      _id: '3',
      name: 'Hard Copy Bond Paper',
      slug: 'hardcopy-a4-bond-paper',
      category: 'Office Supplies',
      size: 'A4 (8.3"x 11.7")',
      image: '/images/p3.jpg',
      price: 187.57,
      countInStock: 0,
      brand: 'Dong-A',
      rating: 4.8,
      numReviews: 30,
      description: 'subs-20/70gsm, high quality bond paper',
    },
  ],
};

export default data;
